import 'server-only';
import crypto from 'node:crypto';
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';

import { isAdminConfigured } from '@/lib/env';
import { signValue, verifyValue, safeEqual } from '@/lib/signed-value';

/**
 * Admin authentication.
 *
 * Design decisions:
 *  - Passwords are never stored. ADMIN_PASSWORD_HASH holds a scrypt hash with a
 *    per-password salt, generated by `npm run admin:hash`.
 *  - The session is an HMAC-signed, expiring value in an httpOnly, SameSite=Lax,
 *    Secure cookie. There is no client-readable session state, so no client-side
 *    check can be bypassed to reach admin data.
 *  - Every admin page and action calls `requireAdmin()` on the server. The check
 *    is authoritative there, not in middleware or in the browser.
 *  - When the environment is not fully configured, the admin area is disabled
 *    outright rather than falling back to a weaker check.
 */

const SESSION_COOKIE = 'havoheal_admin_session';
const SESSION_TTL_SECONDS = 60 * 60 * 8; // 8 hours

const SCRYPT_KEYLEN = 64;

/** Produces "scrypt$<salt-hex>$<hash-hex>" for ADMIN_PASSWORD_HASH. */
export function hashPassword(password: string): string {
  const salt = crypto.randomBytes(16);
  const derived = crypto.scryptSync(password, salt, SCRYPT_KEYLEN);
  return `scrypt$${salt.toString('hex')}$${derived.toString('hex')}`;
}

/** Constant-time password verification. Returns false on any malformed input. */
export function verifyPassword(password: string, stored: string): boolean {
  const parts = stored.split('$');
  if (parts.length !== 3 || parts[0] !== 'scrypt') return false;

  const [, saltHex, hashHex] = parts as [string, string, string];
  try {
    const salt = Buffer.from(saltHex, 'hex');
    const expected = Buffer.from(hashHex, 'hex');
    if (expected.length !== SCRYPT_KEYLEN) return false;

    const derived = crypto.scryptSync(password, salt, SCRYPT_KEYLEN);
    return crypto.timingSafeEqual(derived, expected);
  } catch {
    return false;
  }
}

export type AdminSession = { email: string };

/** Current admin session, or null. Never throws. */
export async function getAdminSession(): Promise<AdminSession | null> {
  if (!isAdminConfigured()) return null;

  const token = (await cookies()).get(SESSION_COOKIE)?.value;
  const email = verifyValue(token);
  if (!email) return null;

  // The session is only valid for the currently configured admin account, so
  // changing ADMIN_EMAIL immediately invalidates old sessions.
  const configured = process.env.ADMIN_EMAIL;
  if (!configured || !safeEqual(email, configured)) return null;

  return { email };
}

/** Server-side gate for admin pages. Redirects instead of rendering. */
export async function requireAdmin(): Promise<AdminSession> {
  if (!isAdminConfigured()) redirect('/admin/setup-required');

  const session = await getAdminSession();
  if (!session) redirect('/admin/login');
  return session;
}

export async function createAdminSession(email: string): Promise<void> {
  const cookieStore = await cookies();
  cookieStore.set(SESSION_COOKIE, signValue(email, SESSION_TTL_SECONDS), {
    httpOnly: true,
    sameSite: 'lax',
    secure: process.env.NODE_ENV === 'production',
    path: '/',
    maxAge: SESSION_TTL_SECONDS,
  });
}

export async function destroyAdminSession(): Promise<void> {
  (await cookies()).delete(SESSION_COOKIE);
}

/** Verifies submitted credentials against the configured admin account. */
export function checkAdminCredentials(email: string, password: string): boolean {
  const configuredEmail = process.env.ADMIN_EMAIL;
  const configuredHash = process.env.ADMIN_PASSWORD_HASH;
  if (!configuredEmail || !configuredHash) return false;

  // Both checks always run so the response time does not reveal which failed.
  const emailOk = safeEqual(email.trim().toLowerCase(), configuredEmail.trim().toLowerCase());
  const passwordOk = verifyPassword(password, configuredHash);
  return emailOk && passwordOk;
}
