import type { Metadata, Viewport } from 'next';
import { Inter, Fraunces } from 'next/font/google';
import './globals.css';

import { Header } from '@/components/layout/header';
import { Footer } from '@/components/layout/footer';
import { MobileActionBar } from '@/components/layout/mobile-action-bar';
import { ConsentBanner } from '@/components/layout/consent-banner';
import { JsonLd } from '@/components/seo/json-ld';
import { siteConfig } from '@/config/site';
import { getSiteUrl } from '@/lib/seo';
import { jsonLdGraph, organizationSchema, websiteSchema } from '@/lib/structured-data';

/**
 * Fonts are self-hosted by next/font at build time: no request to a third-party
 * font CDN at runtime, no layout shift (fallback metrics are adjusted
 * automatically), and no extra connection to negotiate.
 */
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
  preload: true,
});

const fraunces = Fraunces({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-display',
  // Only the two weights the design uses are downloaded, keeping the font
  // payload small.
  weight: ['600', '700'],
  preload: true,
});

export const metadata: Metadata = {
  metadataBase: new URL(getSiteUrl()),
  title: {
    default: 'Physiotherapy Birmingham | 45-Minute Appointments | Havoheal',
    template: `%s`,
  },
  description: siteConfig.description,
  applicationName: siteConfig.name,
  authors: [{ name: siteConfig.legalName }],
  creator: siteConfig.legalName,
  publisher: siteConfig.legalName,
  formatDetection: { telephone: true, email: true, address: false },
  category: 'health',
  referrer: 'strict-origin-when-cross-origin',
  alternates: { canonical: '/' },
  openGraph: {
    type: 'website',
    locale: 'en_GB',
    siteName: siteConfig.name,
    url: getSiteUrl(),
  },
  twitter: { card: 'summary_large_image' },
  // The apple touch icon is generated by src/app/apple-icon.tsx and picked up
  // automatically, so it is not listed here.
  icons: {
    icon: [{ url: '/favicon.svg', type: 'image/svg+xml' }],
  },
  manifest: '/site.webmanifest',
};

export const viewport: Viewport = {
  themeColor: '#07827e',
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en-GB" className={`${inter.variable} ${fraunces.variable}`}>
      <body className="flex min-h-dvh flex-col bg-white font-sans text-ink">
        {/* Skip link — the first focusable element on every page. */}
        <a href="#main-content" className="skip-link">
          Skip to main content
        </a>

        <Header />

        <main id="main-content" tabIndex={-1} className="flex-1 pb-mobile-bar">
          {children}
        </main>

        <Footer />
        <MobileActionBar />
        <ConsentBanner />

        {/* Site-wide Organization and WebSite graph. */}
        <JsonLd data={jsonLdGraph(organizationSchema(), websiteSchema())} />
      </body>
    </html>
  );
}
